/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyNftsRouteImport } from './routes/my-nfts'
import { Route as MintRouteImport } from './routes/mint'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MintCollectionIdRouteImport } from './routes/mint.$collectionId'

const MyNftsRoute = MyNftsRouteImport.update({
  id: '/my-nfts',
  path: '/my-nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MintCollectionIdRoute = MintCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => MintRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mint': typeof MintRouteWithChildren
  '/my-nfts': typeof MyNftsRoute
  '/mint/$collectionId': typeof MintCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mint': typeof MintRouteWithChildren
  '/my-nfts': typeof MyNftsRoute
  '/mint/$collectionId': typeof MintCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mint': typeof MintRouteWithChildren
  '/my-nfts': typeof MyNftsRoute
  '/mint/$collectionId': typeof MintCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mint' | '/my-nfts' | '/mint/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mint' | '/my-nfts' | '/mint/$collectionId'
  id: '__root__' | '/' | '/mint' | '/my-nfts' | '/mint/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MintRoute: typeof MintRouteWithChildren
  MyNftsRoute: typeof MyNftsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-nfts': {
      id: '/my-nfts'
      path: '/my-nfts'
      fullPath: '/my-nfts'
      preLoaderRoute: typeof MyNftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint/$collectionId': {
      id: '/mint/$collectionId'
      path: '/$collectionId'
      fullPath: '/mint/$collectionId'
      preLoaderRoute: typeof MintCollectionIdRouteImport
      parentRoute: typeof MintRoute
    }
  }
}

interface MintRouteChildren {
  MintCollectionIdRoute: typeof MintCollectionIdRoute
}

const MintRouteChildren: MintRouteChildren = {
  MintCollectionIdRoute: MintCollectionIdRoute,
}

const MintRouteWithChildren = MintRoute._addFileChildren(MintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MintRoute: MintRouteWithChildren,
  MyNftsRoute: MyNftsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
